global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.1.129:9090']

  - job_name: 'kafka_exporter'
    static_configs:
      - targets: ['192.168.1.129:9308']